server:
  port: 80
#mybatis配置
mybatis:
  #扫描映射文件
  mapper-locations: classpath:mapper/*.xml
  #指定别名所在的包
  type-aliases-package: cn.fudan.entity
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true

#连接数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/firstdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
#试图前缀和后缀
#设置日志级别
logging:
  level:
    cn.fudan.mapper: debug
